### ISSUE TITLE
Description field of function not supported

### ISSUE THREAD

**Issue by korridor** [scaleway/serverless-scaleway-functions#112]
If I set the `description` of a function like this:

```yaml
functions:
  hello:
     # ...
    description: "Description of what the function does"
     # ...
```

it would be great if this sets the Description field of the function/container in the Scaleway Console.

Screenshot of the field in the Scaleway Console:
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/26689068/189526867-3549c8d5-59b3-402d-bfb9-674f8be6d15b.png">
