### ISSUE TITLE
Undetailed error on deployment

### ISSUE THREAD

**Issue by alburni** [scaleway/serverless-scaleway-functions#38]
Im trying to deploy a container which works well in a local Docker environment.

Stacktrace:
```
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Packaging service...
Serverless: Updating container first...
Serverless: Building and pushing container first to: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ...
Serverless: Deploying Containers...
Serverless: Waiting for container deployments, this may take multiple minutes...

 Error ---------------------------------------------------

  Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error:
Error: Error: Error: Error: Error: Error: Error: Error: internal error
      at manageError (/home/benjamin/armada-lex/node_modules/serverless-scaleway-functions/shared/api/utils.js:20:11)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              10.24.0
     Framework Version:         2.33.0
     Plugin Version:            4.5.3
     SDK Version:               4.2.2
     Components Version:        3.8.1
```

serverless.yaml
```
service:
  name: staging

provider:
  name: scaleway
  # Global Environment variables - used in every functions
  env:
    # env variables here...
  # the path to the credentials file needs to be absolute
  scwToken: XXXXXXXXXXXXXXXXXXXXX
  scwOrganization: XXXXXXXXXXXXXXXXXXXXX

plugins:
  - serverless-scaleway-functions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

custom:
  containers:
    backend:
      directory: backend
      minScale: 1
      memoryLimit: 2048
      maxScale: 1
      # timeout: 20000
```
