### ISSUE TITLE
While deploying: An error occured while getting a presigned URL to upload functions's archived code.

### ISSUE THREAD

**Issue by dimitrilahaye** [scaleway/serverless-scaleway-functions#82]
Hello,
I have this error during the deployment of my function:

> An error occured while getting a presigned URL to upload functions's archived code.

Below are my environment information:

```
     Operating System:          linux
     Node Version:              14.17.6
     Framework Version:         2.72.3 (local)
     Plugin Version:            5.5.4
     SDK Version:               4.3.2
     Components Version:        3.18.2
```

And below my serverless.yaml

```yaml
service: my-app
configValidationMode: off
variablesResolutionMode: 20210326
scwRegion: fr-par
provider:
    name: scaleway
    runtime: node14 # Available node runtimes are listed in documentation
    # Global Environment variables - used in every functions
    env:
        test: test
    # the path to the credentials file needs to be absolute
    scwToken: ${env:SCWTOKEN}
    scwProject: ${env:SCWPROJECT}

plugins:
    - serverless-scaleway-functions

package:
    patterns:
        - "!.gitignore"
        - "!.git/**"
        - './node_modules/**'

functions:
    myfunction:
        handler: dist/src/consumers/handlers/myfunctionhandler.handle

```

Do you have an idea of what is happening?
