### ISSUE TITLE
Error while deploying container

### ISSUE THREAD

**Issue by milanjandric** [scaleway/serverless-scaleway-functions#94]
I'm trying to run my first container. 
I have tried first manually to do so by pushing the image and creating Container using the web console. After I try to deploy I get only "Container failed with: .' when hovering over the red circle. 

Then I tried to deploy using serverless and by using just your container example.
`serverless create --path my-func --template-url https://github.com/scaleway/serverless-scaleway-functions/tree/master/examples/container`

```
service: my-func
configValidationMode: off
useDotenv: true

provider:
  name: scaleway
  # Global Environment variables - used in every functions
  env:
    test: test
  # the path to the credentials file needs to be absolute
  scwToken: ${env:SCW_SECRET_KEY}
  scwProject: ${env:SCW_DEFAULT_PROJECT_ID}
  scwRegion: ${env:SCW_REGION}

plugins:
  - serverless-scaleway-functions

package:
  patterns:
    - '!node_modules/**'
    - '!.gitignore'
    - '!.git/**'

custom:
  containers:
    first:
      directory: my-container
      minScale: 1
      memoryLimit: 256
      maxScale: 2
      port: 8080
      # Local environment variables - used only in given function
      env:
        local: local`
```

And I do get the same error but in a different format

```
serverless deploy
Using credentials from system environment
Using credentials from system environment
Using credentials from system environment
Using credentials from system environment
Using credentials from system environment
Using credentials from system environment
Creating container first...
Building and pushing container first to: rg.fr-par.scw.cloud/funcscwmyfuncjqb8s2em/first:latest ...
Deploying Containers...
Waiting for container deployments, this may take multiple minutes...
Environment: darwin, node 18.1.0, framework 3.19.0, plugin 6.2.2, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Error: Container failed with: .
    at manageError (/Users/milan/Documents/Projects/pitchflow/test-serverless/my-func/node_modules/serverless-scaleway-functions/shared/api/utils.js:20:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

What am I doing wrong or there is some problem on your side?

Also, strange thing is that when I look at images in Container Registry, all images have the size of 0bytes.
